[workspace]

[package]
name = "houdini-node"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.30.4"
serde = { version = "1.0.219", features = ["serde_derive"] }
thiserror = "2.0.12"
serde_json = "1.0.141"
itertools = "0.14.0"
houdini-node-macro = { path = "packages/houdini-node-macro" }